Improved awstats_site resource
osuosl-cookbooks/osl-resources pull request #12
Opened 2022-09-02 21:31 UTC by OniLink

2022-09-06 17:20 UTC, ramereth requested changes

2022-09-06 17:20 UTC, ramereth commented on resources/osl_awstats_site.rb
> +).join(' ')
Move this to a helper method and then call it like this:
```suggestion
property :log_format, String, default: lazy { new_helper_method_name }
```

2022-09-06 17:20 UTC, ramereth commented on resources/osl_awstats_site.rb
> +    only_files = only_files.join(' ') if only_files.is_a?(Array)
It looks like this might be better as a library helper method instead. I'd move the logic there and then just call it here.

2022-09-09 17:38 UTC, ramereth requested changes
Looks like you never added spec tests for this resource, would you mind please doing that?

2022-09-09 17:38 UTC, ramereth commented on resources/osl_awstats_site.rb
> +    log_file = ''
I don't think this is needed technically.

2022-09-21 16:15 UTC, ramereth requested changes
I'd feel better if you had more thorough InSpec tests which checked that each line of the file is formatted exactly with the content you expect. Since you're modifying a lot of the formation of each line, I think it's important to make sure we get that right.

So close otherwise!

2022-09-23 20:08 UTC, OniLink commented
The most thorough tests are done on awstats.test.osuosl.org.conf and awstats.test-full.conf. The other two test files are for more specific options, but this should cover the variable aspects of the file. I could make the LogFile test a tad more extensive but this should cover everything and it's already fairly long.

2022-09-26 18:00 UTC, ramereth approved these changes
Patch bump

2022-09-26 18:06 UTC, OniLink commented
!bump patch ~

2022-09-26 18:07 UTC, merged

2022-09-26 18:07 UTC, osuosl-manatee commented
Jenkins has merged this PR into `main` and has automatically performed a patch-level version bump to v1.3.1.  Have a nice day!