removing-support-debian-10
osuosl-cookbooks/osl-resources pull request #2
Opened 2022-01-09 20:27 UTC by FrankreedX

2022-01-13 22:17 UTC, ramereth requested changes

2022-01-14 17:29 UTC, ramereth approved these changes
Patch bump

2022-01-14 19:42 UTC, FrankreedX commented
!bump minor ~

2022-01-14 19:42 UTC, merged

2022-01-14 19:43 UTC, osuosl-manatee commented
Jenkins has merged this PR into `main` and has automatically performed a minor-level version bump to v1.1.0.  Have a nice day!