Initial Hugo resource
osuosl-cookbooks/osl-resources pull request #23
Opened 2023-12-01 21:37 UTC by pasimko

2024-01-02 19:55 UTC, ramereth requested changes
Great start! Don't forget to add spec tests.

2024-01-02 19:55 UTC, ramereth commented on resources/osl_hugo.rb
> +  end
Please add a symlink `/usr/local/bin/hugo` to `/opt/hugo/hugo`

2024-01-02 19:55 UTC, ramereth commented on test/integration/osl_hugo/controls/osl_hugo.rb
> +  end
Let's replace these tests with a command test with `hugo version` returning the version you expect with an exit status of 0

2024-01-02 19:55 UTC, ramereth commented on test/integration/osl_hugo/controls/osl_hugo.rb
> +    it { should exist }
Also add the size is greater than zero.

2024-01-02 19:55 UTC, ramereth commented on test/integration/osl_hugo/controls/osl_hugo.rb
> +  end
Add a test for the symlink.

2024-01-29 18:34 UTC, ramereth commented on kitchen.yml
> +      multiple_converge: 1
Please fix this

2024-02-09 19:31 UTC, ramereth commented on kitchen.yml
> +      multiple_converge: 2
Please remove this, it will pull this from the global config above.

2024-02-09 23:52 UTC, ramereth approved these changes
Minor bump

2024-02-16 22:51 UTC, pasimko commented
!bump minor ~

2024-02-16 22:51 UTC, merged

2024-02-16 22:51 UTC, osuosl-manatee commented
Jenkins has merged this PR into `main` and has automatically performed a minor-level version bump to v1.8.0.  Have a nice day!